# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yangjin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('day', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Yangsung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('day', models.TextField()),
            ],
        ),
    ]
