# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_yangjin_yangsung'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('day', models.TextField()),
            ],
        ),
    ]
